language: go

go:
  - 1.7
  - 1.6
  - 1.7.1
  - tip

before_install:
  - git clone https://github.com/kr/beanstalkd && cd beanstalkd
  - ls -al
  - nohup ./beanstalkd &
  - cd ..

script: go test -v ./...